version: "3.8"
services:
  api:
    image: nisal/api:latest
    ports:
      - "5000:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1qaz2wsx@