version: "3.8"
services:
  api:
    image: nisal/api:latest
    ports:
      - "5000:80"
  web:
    image: nisal/web:latest
    ports:
      - "4200:80"
  sqlserver:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - ACCEPT_EULA=Y
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=1qaz2wsx@